name: free_dict
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  sqflite: ^2.4.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  http: ^1.2.0
  just_audio: ^0.9.36
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/words_dictionary.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/free_dict_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/free_dict_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logos/free_dict_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logos/free_dict_logo.png"
